server:
  http2:
    enabled: true

supabase:
  url: ${SUPABASE_URL:https://tejxnmdirdoauqjffpph.supabase.co/storage/v1/s3}
  key: ${SUPABASE_KEY:0ad52b1be44b28cdf7dbd5cc9abc4082}
  bucket: ${SUPABASE_BUCKET:Qldapm}

spring:
  datasource:
    url: ${SUPABASE_DB_URL:jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres}
    username: ${SUPABASE_DB_USER:postgres.tejxnmdirdoauqjffpph}
    password: ${SUPABASE_DB_PASSWORD:89PBR0XIvsRQBRyi}
    hikari:
      pool-name: SpringBootBoilerplateHikariPool
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jta:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: phamducthang2508@gmail.com
    password: jqoaqrlhkdzqjdxz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  # File upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2KB

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

# File Storage Configuration
file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.farukgenc.boilerplate.springboot: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: secret
  issuer: www.farukgenc.com
  expirationMinute: 10

swagger:
  contact-name: Faruk Genc
  contact-mail: omer@farukgenc.com
  contact-url: https://farukgenc.com
  app-name: Spring Boot Boilerplate Project
  app-description: "Spring Boot Boilerplate is a starter kit. This project includes : Spring Boot(3.4.0), Spring Data JPA, Spring Validation, Spring Security + JWT Token, PostgreSQL, Mapstruct, Lombok, Swagger (Open API)"
  app-version: 3.4.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
